dist: bionic
language: python
python:
  - "3.7"

install:
  - pip install flake8

script:
  - flake8 --max-line-length=160 ./
  - flake8 --ignore = E226,E302,E41 ./ 
  - flake8 --exclude = tests/* ./
  - flake8 --max-complexity = 10 ./  
